#!/bin/bash
# Project Structure Visualization

echo "===================================="
echo "  CHARLIE - CLEAN STRUCTURE"
echo "===================================="
echo ""
echo "Final Project/"
echo "│"
echo "├── src/charlie/              FASE 1 - Local Development"
echo "│   │"
echo "│   ├── sense/                SENSE (Detection)"
echo "│   │   ├── yolo_detector.py"
echo "│   │   └── frame_reader.py"
echo "│   │"
echo "│   ├── plan/                 PLAN (Behavior Tree)"
echo "│   │   └── behavior_tree_node.py"
echo "│   │"
echo "│   ├── act/                  ACT (Control)"
echo "│   │   └── controller.py"
echo "│   │"
echo "│   ├── utils/                Utilities"
echo "│   │   └── visualizer.py"
echo "│   │"
echo "│   ├── main.py               Entry Point"
echo "│   │"
echo "│   └── ros2_wrappers/        FASE 2 - ROS2 Deployment"
echo "│       ├── perception_node.py"
echo "│       ├── navigation_node.py"
echo "│       ├── detection.py (legacy)"
echo "│       ├── launch/"
echo "│       ├── resource/"
echo "│       ├── setup.py"
echo "│       ├── setup.cfg"
echo "│       └── package.xml"
echo "│"
echo "├── models/                   YOLO Models"
echo "├── data/                     Dataset"
echo "├── scripts/                  Helper Scripts"
echo "│   └── demo.py"
echo "├── tests/                    Tests"
echo "│"
echo "├── requirements.txt          Python deps (FASE 1)"
echo "├── README.md"
echo "│"
echo "└── docker/                   Docker setup (FASE 2)"   
echo "    ├── docker-compose.yml"
echo "    └── Dockerfile"
echo ""
echo "===================================="
echo "Clean Separation: FASE 1 / FASE 2"
echo "===================================="
